// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Radix2wECC_point_add (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x1_V_read,
        y1_V_read,
        x2_V_read,
        y2_V_read,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_state23 = 28'd4194304;
parameter    ap_ST_fsm_state24 = 28'd8388608;
parameter    ap_ST_fsm_state25 = 28'd16777216;
parameter    ap_ST_fsm_state26 = 28'd33554432;
parameter    ap_ST_fsm_state27 = 28'd67108864;
parameter    ap_ST_fsm_state28 = 28'd134217728;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [165:0] x1_V_read;
input  [165:0] y1_V_read;
input  [165:0] x2_V_read;
input  [165:0] y2_V_read;
output  [165:0] ap_return_0;
output  [165:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[165:0] ap_return_0;
reg[165:0] ap_return_1;

(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [165:0] grp_bf_inv_fu_160_ap_return;
reg   [165:0] reg_245;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state19;
wire   [165:0] grp_bf_mult_1_fu_165_ap_return;
reg   [165:0] reg_250;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state26;
wire   [165:0] grp_bf_mult_2_fu_172_ap_return;
reg   [165:0] reg_258;
wire    ap_CS_fsm_state6;
wire   [162:0] trunc_ln99_fu_264_p1;
reg   [162:0] trunc_ln99_reg_478;
wire   [0:0] or_ln100_fu_280_p2;
reg   [0:0] or_ln100_reg_483;
wire   [0:0] icmp_ln101_fu_292_p2;
reg   [0:0] icmp_ln101_reg_487;
wire   [0:0] icmp_ln1019_fu_298_p2;
reg   [0:0] icmp_ln1019_reg_491;
wire   [162:0] trunc_ln120_fu_312_p1;
reg   [162:0] trunc_ln120_reg_501;
wire   [165:0] d_V_4_fu_323_p2;
reg   [165:0] d_V_4_reg_509;
wire    ap_CS_fsm_state10;
wire   [165:0] grp_bf_mult_fu_200_ap_return;
reg   [165:0] a_V_reg_519;
wire    ap_CS_fsm_state13;
wire   [165:0] select_ln108_fu_358_p3;
wire    ap_CS_fsm_state18;
wire   [165:0] lambda_V_5_fu_369_p2;
reg   [165:0] lambda_V_5_reg_538;
wire    ap_CS_fsm_state22;
reg   [165:0] call_ret8_reg_544;
wire    ap_CS_fsm_state23;
wire   [162:0] empty_fu_378_p1;
reg   [162:0] empty_reg_552;
wire    ap_CS_fsm_state25;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_done;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_idle;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_ready;
wire   [165:0] grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out_ap_vld;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_done;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_idle;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_ready;
wire   [162:0] grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out_ap_vld;
wire    grp_bf_inv_fu_160_ap_start;
wire    grp_bf_inv_fu_160_ap_done;
wire    grp_bf_inv_fu_160_ap_idle;
wire    grp_bf_inv_fu_160_ap_ready;
reg   [165:0] grp_bf_inv_fu_160_x_V_read;
wire    grp_bf_mult_1_fu_165_ap_start;
wire    grp_bf_mult_1_fu_165_ap_done;
wire    grp_bf_mult_1_fu_165_ap_idle;
wire    grp_bf_mult_1_fu_165_ap_ready;
reg   [165:0] grp_bf_mult_1_fu_165_z_V_read;
reg   [162:0] grp_bf_mult_1_fu_165_y_V_read;
wire    grp_bf_mult_2_fu_172_ap_start;
wire    grp_bf_mult_2_fu_172_ap_done;
wire    grp_bf_mult_2_fu_172_ap_idle;
wire    grp_bf_mult_2_fu_172_ap_ready;
reg   [165:0] grp_bf_mult_2_fu_172_x_V_read;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_done;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_idle;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_ready;
wire   [165:0] grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_d_V_6_out;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_d_V_6_out_ap_vld;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_done;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_idle;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_ready;
wire   [165:0] grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_p_Val2_12_out;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_p_Val2_12_out_ap_vld;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_done;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_idle;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_ready;
wire   [165:0] grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_p_Val2_16_out;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_p_Val2_16_out_ap_vld;
wire    grp_bf_mult_fu_200_ap_start;
wire    grp_bf_mult_fu_200_ap_done;
wire    grp_bf_mult_fu_200_ap_idle;
wire    grp_bf_mult_fu_200_ap_ready;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_done;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_idle;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_ready;
wire   [165:0] grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_a_V_7_out;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_a_V_7_out_ap_vld;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_done;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_idle;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_ready;
wire   [165:0] grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out_ap_vld;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_done;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_idle;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_ready;
wire   [165:0] grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out_ap_vld;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_done;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_idle;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_ready;
wire   [165:0] grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out_ap_vld;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_done;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_idle;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_ready;
wire   [165:0] grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_p_Val2_14_out;
wire    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_p_Val2_14_out_ap_vld;
reg   [165:0] ap_phi_mux_x1_3_phi_fu_113_p10;
reg   [165:0] x1_3_reg_110;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state28;
wire   [0:0] icmp_ln108_fu_354_p2;
reg   [165:0] ap_phi_mux_y1_2_phi_fu_129_p10;
reg   [165:0] y1_2_reg_125;
reg    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg;
reg   [162:0] p_Val2_8_loc_fu_66;
reg    grp_bf_inv_fu_160_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_bf_mult_1_fu_165_ap_start_reg;
reg    ap_block_state19_on_subcall_done;
reg    grp_bf_mult_2_fu_172_ap_start_reg;
reg    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_bf_mult_fu_200_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
reg    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg;
wire    ap_CS_fsm_state21;
reg    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg;
wire    ap_CS_fsm_state24;
reg    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg;
wire    ap_CS_fsm_state27;
wire   [0:0] icmp_ln1023_fu_268_p2;
wire   [0:0] icmp_ln1023_2_fu_274_p2;
wire   [165:0] or_ln101_fu_286_p2;
reg   [165:0] ap_return_0_preg;
reg   [165:0] ap_return_1_preg;
reg   [27:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg = 1'b0;
#0 grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg = 1'b0;
#0 grp_bf_inv_fu_160_ap_start_reg = 1'b0;
#0 grp_bf_mult_1_fu_165_ap_start_reg = 1'b0;
#0 grp_bf_mult_2_fu_172_ap_start_reg = 1'b0;
#0 grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg = 1'b0;
#0 grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg = 1'b0;
#0 grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg = 1'b0;
#0 grp_bf_mult_fu_200_ap_start_reg = 1'b0;
#0 grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg = 1'b0;
#0 grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg = 1'b0;
#0 grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg = 1'b0;
#0 grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg = 1'b0;
#0 grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg = 1'b0;
#0 ap_return_0_preg = 166'd0;
#0 ap_return_1_preg = 166'd0;
end

Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_17 grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start),
    .ap_done(grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_done),
    .ap_idle(grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_idle),
    .ap_ready(grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_ready),
    .x1_V_read(x1_V_read),
    .x2_V_read(x2_V_read),
    .a_V_6_out(grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out),
    .a_V_6_out_ap_vld(grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out_ap_vld)
);

Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_18 grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start),
    .ap_done(grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_done),
    .ap_idle(grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_idle),
    .ap_ready(grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_ready),
    .y1_V_read(y1_V_read),
    .y2_V_read(y2_V_read),
    .p_Val2_8_out(grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out),
    .p_Val2_8_out_ap_vld(grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out_ap_vld)
);

Radix2wECC_bf_inv grp_bf_inv_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bf_inv_fu_160_ap_start),
    .ap_done(grp_bf_inv_fu_160_ap_done),
    .ap_idle(grp_bf_inv_fu_160_ap_idle),
    .ap_ready(grp_bf_inv_fu_160_ap_ready),
    .x_V_read(grp_bf_inv_fu_160_x_V_read),
    .ap_return(grp_bf_inv_fu_160_ap_return)
);

Radix2wECC_bf_mult_1 grp_bf_mult_1_fu_165(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bf_mult_1_fu_165_ap_start),
    .ap_done(grp_bf_mult_1_fu_165_ap_done),
    .ap_idle(grp_bf_mult_1_fu_165_ap_idle),
    .ap_ready(grp_bf_mult_1_fu_165_ap_ready),
    .z_V_read(grp_bf_mult_1_fu_165_z_V_read),
    .y_V_read(grp_bf_mult_1_fu_165_y_V_read),
    .ap_return(grp_bf_mult_1_fu_165_ap_return)
);

Radix2wECC_bf_mult_2 grp_bf_mult_2_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bf_mult_2_fu_172_ap_start),
    .ap_done(grp_bf_mult_2_fu_172_ap_done),
    .ap_idle(grp_bf_mult_2_fu_172_ap_idle),
    .ap_ready(grp_bf_mult_2_fu_172_ap_ready),
    .x_V_read(grp_bf_mult_2_fu_172_x_V_read),
    .ap_return(grp_bf_mult_2_fu_172_ap_return)
);

Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_19 grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start),
    .ap_done(grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_done),
    .ap_idle(grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_idle),
    .ap_ready(grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_ready),
    .d_V(reg_258),
    .c_V_3(reg_250),
    .d_V_6_out(grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_d_V_6_out),
    .d_V_6_out_ap_vld(grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_d_V_6_out_ap_vld)
);

Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_110 grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start),
    .ap_done(grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_done),
    .ap_idle(grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_idle),
    .ap_ready(grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_ready),
    .d_V_6_reload(grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_d_V_6_out),
    .a_V_6_reload(grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out),
    .p_Val2_12_out(grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_p_Val2_12_out),
    .p_Val2_12_out_ap_vld(grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_p_Val2_12_out_ap_vld)
);

Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_111 grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start),
    .ap_done(grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_done),
    .ap_idle(grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_idle),
    .ap_ready(grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_ready),
    .x1_V_read(x1_V_read),
    .d_V_7(d_V_4_reg_509),
    .p_Val2_16_out(grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_p_Val2_16_out),
    .p_Val2_16_out_ap_vld(grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_p_Val2_16_out_ap_vld)
);

Radix2wECC_bf_mult grp_bf_mult_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bf_mult_fu_200_ap_start),
    .ap_done(grp_bf_mult_fu_200_ap_done),
    .ap_idle(grp_bf_mult_fu_200_ap_idle),
    .ap_ready(grp_bf_mult_fu_200_ap_ready),
    .x_V_read(grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_p_Val2_16_out),
    .y_V_read(trunc_ln120_reg_501),
    .ap_return(grp_bf_mult_fu_200_ap_return)
);

Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_112 grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start),
    .ap_done(grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_done),
    .ap_idle(grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_idle),
    .ap_ready(grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_ready),
    .a_V(a_V_reg_519),
    .d_V_7(d_V_4_reg_509),
    .a_V_7_out(grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_a_V_7_out),
    .a_V_7_out_ap_vld(grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_a_V_7_out_ap_vld)
);

Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_113 grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start),
    .ap_done(grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_done),
    .ap_idle(grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_idle),
    .ap_ready(grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_ready),
    .y1_V_read(y1_V_read),
    .a_V_7_reload(grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_a_V_7_out),
    .p_Val2_19_out(grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out),
    .p_Val2_19_out_ap_vld(grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out_ap_vld)
);

Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_1 grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start),
    .ap_done(grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_done),
    .ap_idle(grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_idle),
    .ap_ready(grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_ready),
    .lambda_V_7(reg_250),
    .x2_V_read(x2_V_read),
    .p_Val2_7_out(grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out),
    .p_Val2_7_out_ap_vld(grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out_ap_vld)
);

Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_15 grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start),
    .ap_done(grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_done),
    .ap_idle(grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_idle),
    .ap_ready(grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_ready),
    .call_ret8(call_ret8_reg_544),
    .lambda_V_11(lambda_V_5_reg_538),
    .p_Val2_9_out(grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out),
    .p_Val2_9_out_ap_vld(grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out_ap_vld)
);

Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_16 grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start),
    .ap_done(grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_done),
    .ap_idle(grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_idle),
    .ap_ready(grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_ready),
    .call_ret7(reg_258),
    .lambda_V_12(reg_250),
    .p_Val2_14_out(grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_p_Val2_14_out),
    .p_Val2_14_out_ap_vld(grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_p_Val2_14_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 166'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            ap_return_0_preg <= ap_phi_mux_x1_3_phi_fu_113_p10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 166'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            ap_return_1_preg <= ap_phi_mux_y1_2_phi_fu_129_p10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bf_inv_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) | ((icmp_ln108_fu_354_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18)))) begin
            grp_bf_inv_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_bf_inv_fu_160_ap_ready == 1'b1)) begin
            grp_bf_inv_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bf_mult_1_fu_165_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state25) | ((1'b1 == ap_CS_fsm_state4) & (grp_bf_inv_fu_160_ap_done == 1'b1)) | ((1'b0 == ap_block_state19_on_subcall_done) & (1'b1 == ap_CS_fsm_state19)))) begin
            grp_bf_mult_1_fu_165_ap_start_reg <= 1'b1;
        end else if ((grp_bf_mult_1_fu_165_ap_ready == 1'b1)) begin
            grp_bf_mult_1_fu_165_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bf_mult_2_fu_172_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state22) | ((1'b1 == ap_CS_fsm_state5) & (grp_bf_mult_1_fu_165_ap_done == 1'b1)) | ((icmp_ln108_fu_354_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18)))) begin
            grp_bf_mult_2_fu_172_ap_start_reg <= 1'b1;
        end else if ((grp_bf_mult_2_fu_172_ap_ready == 1'b1)) begin
            grp_bf_mult_2_fu_172_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bf_mult_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_bf_mult_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_bf_mult_fu_200_ap_ready == 1'b1)) begin
            grp_bf_mult_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_ready == 1'b1)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_ready == 1'b1)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_bf_mult_fu_200_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_ready == 1'b1)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_ready == 1'b1)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state23) & (grp_bf_mult_2_fu_172_ap_done == 1'b1))) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_ready == 1'b1)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state26) & (grp_bf_mult_1_fu_165_ap_done == 1'b1))) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_ready == 1'b1)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1019_fu_298_p2 == 1'd0) & (icmp_ln101_fu_292_p2 == 1'd0) & (or_ln100_fu_280_p2 == 1'd0))) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_ready == 1'b1)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1019_fu_298_p2 == 1'd0) & (icmp_ln101_fu_292_p2 == 1'd0) & (or_ln100_fu_280_p2 == 1'd0))) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_ready == 1'b1)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (grp_bf_mult_2_fu_172_ap_done == 1'b1))) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_ready == 1'b1)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state20) & (grp_bf_mult_1_fu_165_ap_done == 1'b1))) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_ready == 1'b1)) begin
            grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln108_fu_354_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        x1_3_reg_110 <= select_ln108_fu_358_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln101_fu_292_p2 == 1'd1) & (or_ln100_fu_280_p2 == 1'd0))) begin
        x1_3_reg_110 <= x2_V_read;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln100_fu_280_p2 == 1'd1))) begin
        x1_3_reg_110 <= x1_V_read;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        x1_3_reg_110 <= grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out;
    end else if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln1019_reg_491 == 1'd0) & (icmp_ln101_reg_487 == 1'd0) & (or_ln100_reg_483 == 1'd0))) begin
        x1_3_reg_110 <= d_V_4_reg_509;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln108_fu_354_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        y1_2_reg_125 <= 166'd0;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln101_fu_292_p2 == 1'd1) & (or_ln100_fu_280_p2 == 1'd0))) begin
        y1_2_reg_125 <= y2_V_read;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln100_fu_280_p2 == 1'd1))) begin
        y1_2_reg_125 <= y1_V_read;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        y1_2_reg_125 <= grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_p_Val2_14_out;
    end else if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln1019_reg_491 == 1'd0) & (icmp_ln101_reg_487 == 1'd0) & (or_ln100_reg_483 == 1'd0))) begin
        y1_2_reg_125 <= grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        a_V_reg_519 <= grp_bf_mult_fu_200_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        call_ret8_reg_544 <= grp_bf_mult_2_fu_172_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        d_V_4_reg_509 <= d_V_4_fu_323_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        empty_reg_552 <= empty_fu_378_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln101_fu_292_p2 == 1'd0) & (or_ln100_fu_280_p2 == 1'd0))) begin
        icmp_ln1019_reg_491 <= icmp_ln1019_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (or_ln100_fu_280_p2 == 1'd0))) begin
        icmp_ln101_reg_487 <= icmp_ln101_fu_292_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        lambda_V_5_reg_538 <= lambda_V_5_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        or_ln100_reg_483 <= or_ln100_fu_280_p2;
        trunc_ln99_reg_478 <= trunc_ln99_fu_264_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out_ap_vld == 1'b1))) begin
        p_Val2_8_loc_fu_66 <= grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_245 <= grp_bf_inv_fu_160_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_250 <= grp_bf_mult_1_fu_165_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state19))) begin
        reg_258 <= grp_bf_mult_2_fu_172_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        trunc_ln120_reg_501 <= trunc_ln120_fu_312_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_bf_mult_fu_200_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state19_on_subcall_done)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_bf_mult_1_fu_165_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((grp_bf_mult_2_fu_172_ap_done == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((grp_bf_mult_1_fu_165_ap_done == 1'b0)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_done == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_bf_inv_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_bf_mult_1_fu_165_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_bf_mult_2_fu_172_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln1019_reg_491 == 1'd0) & (icmp_ln101_reg_487 == 1'd0) & (or_ln100_reg_483 == 1'd0))) begin
        ap_phi_mux_x1_3_phi_fu_113_p10 = d_V_4_reg_509;
    end else begin
        ap_phi_mux_x1_3_phi_fu_113_p10 = x1_3_reg_110;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln1019_reg_491 == 1'd0) & (icmp_ln101_reg_487 == 1'd0) & (or_ln100_reg_483 == 1'd0))) begin
        ap_phi_mux_y1_2_phi_fu_129_p10 = grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out;
    end else begin
        ap_phi_mux_y1_2_phi_fu_129_p10 = y1_2_reg_125;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_return_0 = ap_phi_mux_x1_3_phi_fu_113_p10;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_return_1 = ap_phi_mux_y1_2_phi_fu_129_p10;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_bf_inv_fu_160_x_V_read = x2_V_read;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_bf_inv_fu_160_x_V_read = grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out;
    end else begin
        grp_bf_inv_fu_160_x_V_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_bf_mult_1_fu_165_y_V_read = empty_reg_552;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_bf_mult_1_fu_165_y_V_read = trunc_ln99_reg_478;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_bf_mult_1_fu_165_y_V_read = p_Val2_8_loc_fu_66;
    end else begin
        grp_bf_mult_1_fu_165_y_V_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_bf_mult_1_fu_165_z_V_read = lambda_V_5_reg_538;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state5))) begin
        grp_bf_mult_1_fu_165_z_V_read = reg_245;
    end else begin
        grp_bf_mult_1_fu_165_z_V_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_bf_mult_2_fu_172_x_V_read = grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_bf_mult_2_fu_172_x_V_read = x2_V_read;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_bf_mult_2_fu_172_x_V_read = reg_250;
    end else begin
        grp_bf_mult_2_fu_172_x_V_read = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1019_fu_298_p2 == 1'd1) & (icmp_ln101_fu_292_p2 == 1'd0) & (or_ln100_fu_280_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1019_fu_298_p2 == 1'd0) & (icmp_ln101_fu_292_p2 == 1'd0) & (or_ln100_fu_280_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((icmp_ln101_fu_292_p2 == 1'd1) | (or_ln100_fu_280_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_bf_inv_fu_160_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_bf_mult_1_fu_165_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_bf_mult_2_fu_172_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_bf_mult_fu_200_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state18 : begin
            if (((icmp_ln108_fu_354_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((1'b0 == ap_block_state19_on_subcall_done) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (grp_bf_mult_1_fu_165_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((1'b1 == ap_CS_fsm_state23) & (grp_bf_mult_2_fu_172_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((1'b1 == ap_CS_fsm_state26) & (grp_bf_mult_1_fu_165_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state19_on_subcall_done = ((grp_bf_mult_2_fu_172_ap_done == 1'b0) | (grp_bf_inv_fu_160_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_done == 1'b0) | (grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_done == 1'b0));
end

assign d_V_4_fu_323_p2 = (grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_p_Val2_12_out ^ 166'd1);

assign empty_fu_378_p1 = grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out[162:0];

assign grp_bf_inv_fu_160_ap_start = grp_bf_inv_fu_160_ap_start_reg;

assign grp_bf_mult_1_fu_165_ap_start = grp_bf_mult_1_fu_165_ap_start_reg;

assign grp_bf_mult_2_fu_172_ap_start = grp_bf_mult_2_fu_172_ap_start_reg;

assign grp_bf_mult_fu_200_ap_start = grp_bf_mult_fu_200_ap_start_reg;

assign grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start = grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg;

assign grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start = grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg;

assign grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start = grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg;

assign grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start = grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg;

assign grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start = grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg;

assign grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start = grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg;

assign grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start = grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg;

assign grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start = grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg;

assign grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start = grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg;

assign grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start = grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg;

assign icmp_ln1019_fu_298_p2 = ((x1_V_read == x2_V_read) ? 1'b1 : 1'b0);

assign icmp_ln101_fu_292_p2 = ((or_ln101_fu_286_p2 == 166'd0) ? 1'b1 : 1'b0);

assign icmp_ln1023_2_fu_274_p2 = ((y2_V_read == 166'd0) ? 1'b1 : 1'b0);

assign icmp_ln1023_fu_268_p2 = ((x2_V_read == 166'd0) ? 1'b1 : 1'b0);

assign icmp_ln108_fu_354_p2 = ((y1_V_read != y2_V_read) ? 1'b1 : 1'b0);

assign lambda_V_5_fu_369_p2 = (grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out ^ 166'd1);

assign or_ln100_fu_280_p2 = (icmp_ln1023_fu_268_p2 | icmp_ln1023_2_fu_274_p2);

assign or_ln101_fu_286_p2 = (y1_V_read | x1_V_read);

assign select_ln108_fu_358_p3 = ((icmp_ln108_fu_354_p2[0:0] == 1'b1) ? 166'd0 : x2_V_read);

assign trunc_ln120_fu_312_p1 = grp_bf_mult_1_fu_165_ap_return[162:0];

assign trunc_ln99_fu_264_p1 = y2_V_read[162:0];

endmodule //Radix2wECC_point_add
