// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_51_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        trunc_ln48_mid2,
        p_shl_mid2,
        scalar_V,
        slice_V_1_out,
        slice_V_1_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] trunc_ln48_mid2;
input  [7:0] p_shl_mid2;
input  [165:0] scalar_V;
output  [5:0] slice_V_1_out;
output   slice_V_1_out_ap_vld;

reg ap_idle;
reg slice_V_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln51_fu_92_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [5:0] p_Val2_s_fu_46;
reg   [5:0] p_Result_48_fu_143_p4;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_p_Val2_load_16;
reg   [2:0] j_fu_50;
wire   [2:0] j_3_fu_98_p2;
reg   [2:0] ap_sig_allocacmp_j_2;
wire   [5:0] j_cast33_fu_111_p1;
wire   [5:0] add_ln52_1_fu_115_p2;
wire   [7:0] zext_ln52_fu_121_p1;
wire   [7:0] add_ln52_fu_125_p2;
wire   [31:0] zext_ln779_fu_131_p1;
wire   [31:0] j_cast17_fu_107_p1;
wire   [0:0] p_Result_s_fu_135_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

Radix2wECC_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln51_fu_92_p2 == 1'd0)) begin
            j_fu_50 <= j_3_fu_98_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_50 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln51_fu_92_p2 == 1'd0)) begin
            p_Val2_s_fu_46 <= p_Result_48_fu_143_p4;
        end else if ((ap_loop_init == 1'b1)) begin
            p_Val2_s_fu_46 <= 6'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_92_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_j_2 = 3'd0;
    end else begin
        ap_sig_allocacmp_j_2 = j_fu_50;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_p_Val2_load_16 = 6'd0;
    end else begin
        ap_sig_allocacmp_p_Val2_load_16 = p_Val2_s_fu_46;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_92_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        slice_V_1_out_ap_vld = 1'b1;
    end else begin
        slice_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_1_fu_115_p2 = (trunc_ln48_mid2 + j_cast33_fu_111_p1);

assign add_ln52_fu_125_p2 = (zext_ln52_fu_121_p1 + p_shl_mid2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln51_fu_92_p2 = ((ap_sig_allocacmp_j_2 == 3'd6) ? 1'b1 : 1'b0);

assign j_3_fu_98_p2 = (ap_sig_allocacmp_j_2 + 3'd1);

assign j_cast17_fu_107_p1 = ap_sig_allocacmp_j_2;

assign j_cast33_fu_111_p1 = ap_sig_allocacmp_j_2;

always @ (*) begin
    p_Result_48_fu_143_p4 = ap_sig_allocacmp_p_Val2_load_16;
    p_Result_48_fu_143_p4[j_cast17_fu_107_p1] = |(p_Result_s_fu_135_p3);
end

assign p_Result_s_fu_135_p3 = scalar_V[zext_ln779_fu_131_p1];

assign slice_V_1_out = p_Val2_s_fu_46;

assign zext_ln52_fu_121_p1 = add_ln52_1_fu_115_p2;

assign zext_ln779_fu_131_p1 = add_ln52_fu_125_p2;

endmodule //Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_51_6
