// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Radix2wECC_bf_inv (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_V_read,
        ap_return
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [165:0] x_V_read;
output  [165:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_fu_158_p3;
reg   [0:0] tmp_reg_332;
wire    ap_CS_fsm_state5;
wire  signed [16:0] j_1_fu_172_p3;
reg  signed [16:0] j_1_reg_340;
reg   [0:0] tmp_11_reg_346;
wire   [165:0] select_ln67_fu_191_p3;
reg   [165:0] select_ln67_reg_352;
wire    ap_CS_fsm_state6;
wire   [165:0] u_V_fu_210_p3;
reg   [165:0] u_V_reg_357;
wire   [165:0] r_V_fu_247_p3;
reg   [165:0] r_V_reg_362;
wire   [165:0] r_V_1_fu_266_p3;
reg   [165:0] r_V_1_reg_367;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_done;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_idle;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_ready;
wire   [15:0] grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_i_out;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_i_out_ap_vld;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_done;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_idle;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_ready;
wire   [15:0] grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_i_29_out;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_i_29_out_ap_vld;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_done;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_idle;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_ready;
wire   [165:0] grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o_ap_vld;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_done;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_idle;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_ready;
wire   [165:0] grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o;
wire    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o_ap_vld;
reg    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg;
reg    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [165:0] u_V_2_fu_34;
reg    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg;
reg   [165:0] z_V_write_assign_fu_46;
wire    ap_CS_fsm_state2;
reg   [165:0] v_V_1_fu_38;
wire   [165:0] v_V_fu_205_p3;
reg   [165:0] g_V_fu_42;
wire   [165:0] g_V_1_fu_198_p3;
wire   [0:0] icmp_ln1023_fu_116_p2;
wire   [15:0] add_ln18_fu_132_p2;
wire   [15:0] add_ln18_1_fu_142_p2;
wire   [16:0] zext_ln18_fu_138_p1;
wire   [16:0] zext_ln66_fu_148_p1;
wire   [16:0] j_fu_152_p2;
wire   [16:0] sub_ln70_fu_166_p2;
wire  signed [31:0] sext_ln1669_fu_215_p1;
wire   [165:0] zext_ln1669_fu_218_p1;
wire   [16:0] sub_ln1669_fu_228_p2;
wire  signed [31:0] sext_ln1669_1_fu_233_p1;
wire   [165:0] zext_ln1669_1_fu_237_p1;
wire   [165:0] ashr_ln1669_fu_241_p2;
wire   [165:0] shl_ln1669_fu_222_p2;
wire   [165:0] ashr_ln1669_1_fu_260_p2;
wire   [165:0] shl_ln1669_1_fu_254_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_block_state8_on_subcall_done;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg = 1'b0;
#0 grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg = 1'b0;
#0 grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg = 1'b0;
#0 grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg = 1'b0;
end

Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_15_1 grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start),
    .ap_done(grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_done),
    .ap_idle(grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_idle),
    .ap_ready(grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_ready),
    .u_V_4(u_V_2_fu_34),
    .i_out(grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_i_out),
    .i_out_ap_vld(grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_i_out_ap_vld)
);

Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_15_117 grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start),
    .ap_done(grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_done),
    .ap_idle(grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_idle),
    .ap_ready(grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_ready),
    .v_V_2(v_V_1_fu_38),
    .i_29_out(grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_i_29_out),
    .i_29_out_ap_vld(grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_i_29_out_ap_vld)
);

Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_23_1 grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start),
    .ap_done(grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_done),
    .ap_idle(grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_idle),
    .ap_ready(grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_ready),
    .u_V(u_V_reg_357),
    .r_V(r_V_reg_362),
    .u_V_5_out_i(u_V_2_fu_34),
    .u_V_5_out_o(grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o),
    .u_V_5_out_o_ap_vld(grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o_ap_vld)
);

Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_23_118 grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start),
    .ap_done(grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_done),
    .ap_idle(grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_idle),
    .ap_ready(grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_ready),
    .select_ln67(select_ln67_reg_352),
    .r_V_1(r_V_1_reg_367),
    .p_Val2_33_out_i(z_V_write_assign_fu_46),
    .p_Val2_33_out_o(grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o),
    .p_Val2_33_out_o_ap_vld(grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg <= 1'b1;
        end else if ((grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_ready == 1'b1)) begin
            grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_ready == 1'b1)) begin
            grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg <= 1'b1;
        end else if ((grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_ready == 1'b1)) begin
            grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg <= 1'b1;
        end else if ((grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_ready == 1'b1)) begin
            grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        g_V_fu_42 <= 166'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        g_V_fu_42 <= g_V_1_fu_198_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        u_V_2_fu_34 <= x_V_read;
    end else if (((grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        u_V_2_fu_34 <= grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        v_V_1_fu_38 <= 166'd11692013098647223345629478661730264157247460344009;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        v_V_1_fu_38 <= v_V_fu_205_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        z_V_write_assign_fu_46 <= 166'd1;
    end else if (((grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        z_V_write_assign_fu_46 <= grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_1_reg_340 <= j_1_fu_172_p3;
        tmp_11_reg_346 <= j_1_fu_172_p3[32'd16];
        tmp_reg_332 <= j_fu_152_p2[32'd16];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        r_V_1_reg_367 <= r_V_1_fu_266_p3;
        r_V_reg_362 <= r_V_fu_247_p3;
        select_ln67_reg_352 <= select_ln67_fu_191_p3;
        u_V_reg_357 <= u_V_fu_210_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state8_on_subcall_done)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln1023_fu_116_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1023_fu_116_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1023_fu_116_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln18_1_fu_142_p2 = (grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_i_29_out + 16'd1);

assign add_ln18_fu_132_p2 = (grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_i_out + 16'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_done == 1'b0) | (grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state8_on_subcall_done = ((grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_done == 1'b0) | (grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_done == 1'b0));
end

assign ap_return = z_V_write_assign_fu_46;

assign ashr_ln1669_1_fu_260_p2 = $signed(g_V_1_fu_198_p3) >>> zext_ln1669_1_fu_237_p1;

assign ashr_ln1669_fu_241_p2 = $signed(v_V_fu_205_p3) >>> zext_ln1669_1_fu_237_p1;

assign g_V_1_fu_198_p3 = ((tmp_reg_332[0:0] == 1'b1) ? z_V_write_assign_fu_46 : g_V_fu_42);

assign grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start = grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg;

assign grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start = grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg;

assign grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start = grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg;

assign grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start = grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg;

assign icmp_ln1023_fu_116_p2 = ((u_V_2_fu_34 == 166'd1) ? 1'b1 : 1'b0);

assign j_1_fu_172_p3 = ((tmp_fu_158_p3[0:0] == 1'b1) ? sub_ln70_fu_166_p2 : j_fu_152_p2);

assign j_fu_152_p2 = (zext_ln18_fu_138_p1 - zext_ln66_fu_148_p1);

assign r_V_1_fu_266_p3 = ((tmp_11_reg_346[0:0] == 1'b1) ? ashr_ln1669_1_fu_260_p2 : shl_ln1669_1_fu_254_p2);

assign r_V_fu_247_p3 = ((tmp_11_reg_346[0:0] == 1'b1) ? ashr_ln1669_fu_241_p2 : shl_ln1669_fu_222_p2);

assign select_ln67_fu_191_p3 = ((tmp_reg_332[0:0] == 1'b1) ? g_V_fu_42 : z_V_write_assign_fu_46);

assign sext_ln1669_1_fu_233_p1 = $signed(sub_ln1669_fu_228_p2);

assign sext_ln1669_fu_215_p1 = j_1_reg_340;

assign shl_ln1669_1_fu_254_p2 = g_V_1_fu_198_p3 << zext_ln1669_fu_218_p1;

assign shl_ln1669_fu_222_p2 = v_V_fu_205_p3 << zext_ln1669_fu_218_p1;

assign sub_ln1669_fu_228_p2 = ($signed(17'd0) - $signed(j_1_reg_340));

assign sub_ln70_fu_166_p2 = (17'd0 - j_fu_152_p2);

assign tmp_fu_158_p3 = j_fu_152_p2[32'd16];

assign u_V_fu_210_p3 = ((tmp_reg_332[0:0] == 1'b1) ? v_V_1_fu_38 : u_V_2_fu_34);

assign v_V_fu_205_p3 = ((tmp_reg_332[0:0] == 1'b1) ? u_V_2_fu_34 : v_V_1_fu_38);

assign zext_ln1669_1_fu_237_p1 = $unsigned(sext_ln1669_1_fu_233_p1);

assign zext_ln1669_fu_218_p1 = $unsigned(sext_ln1669_fu_215_p1);

assign zext_ln18_fu_138_p1 = add_ln18_fu_132_p2;

assign zext_ln66_fu_148_p1 = add_ln18_1_fu_142_p2;

endmodule //Radix2wECC_bf_inv
