// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Radix2wECC_bf_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_V_read,
        y_V_read,
        ap_return
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [165:0] x_V_read;
input  [162:0] y_V_read;
output  [165:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [165:0] reg_89;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state5;
wire   [165:0] tmp_V_10_fu_135_p2;
reg   [165:0] tmp_V_10_reg_251;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln46_fu_129_p2;
wire   [0:0] tmp_fu_142_p3;
reg   [0:0] tmp_reg_256;
wire   [0:0] p_Result_s_fu_172_p2;
reg   [0:0] p_Result_s_reg_260;
wire    ap_CS_fsm_state4;
wire    grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_start;
wire    grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_done;
wire    grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_idle;
wire    grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_ready;
wire   [165:0] grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_tmp_V_20_out_o;
wire    grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_tmp_V_20_out_o_ap_vld;
wire    grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_start;
wire    grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_done;
wire    grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_idle;
wire    grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_ready;
wire   [165:0] grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_p_Val2_28_out;
wire    grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_p_Val2_28_out_ap_vld;
reg    grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_start_reg;
reg   [165:0] tmp_V_2_in_in_fu_40;
reg    grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_start_reg;
wire    ap_CS_fsm_state6;
reg   [7:0] br_fu_44;
wire   [7:0] add_ln46_fu_195_p2;
wire    ap_CS_fsm_state7;
reg   [165:0] tmp_V_8_fu_48;
wire   [165:0] tmp_V_fu_98_p3;
reg   [165:0] z_V_write_assign_fu_52;
wire   [0:0] trunc_ln36_fu_94_p1;
wire   [162:0] zext_ln780_fu_158_p1;
wire   [162:0] shl_ln780_fu_161_p2;
wire   [162:0] and_ln780_fu_167_p2;
reg    ap_block_state4_on_subcall_done;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_start_reg = 1'b0;
#0 grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_start_reg = 1'b0;
end

Radix2wECC_bf_mult_Pipeline_VITIS_LOOP_23_1 grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_start),
    .ap_done(grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_done),
    .ap_idle(grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_idle),
    .ap_ready(grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_ready),
    .tmp_V_19(tmp_V_10_reg_251),
    .tmp_V_20_out_i(tmp_V_2_in_in_fu_40),
    .tmp_V_20_out_o(grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_tmp_V_20_out_o),
    .tmp_V_20_out_o_ap_vld(grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_tmp_V_20_out_o_ap_vld)
);

Radix2wECC_bf_mult_Pipeline_VITIS_LOOP_23_116 grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_start),
    .ap_done(grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_done),
    .ap_idle(grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_idle),
    .ap_ready(grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_ready),
    .empty(tmp_V_8_fu_48),
    .tmp_V_21(reg_89),
    .p_Val2_28_out(grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_p_Val2_28_out),
    .p_Val2_28_out_ap_vld(grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_p_Val2_28_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_start_reg <= 1'b1;
        end else if ((grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_ready == 1'b1)) begin
            grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_fu_142_p3 == 1'd1) & (icmp_ln46_fu_129_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_ready == 1'b1)) begin
            grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        br_fu_44 <= 8'd1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        br_fu_44 <= add_ln46_fu_195_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_V_2_in_in_fu_40 <= x_V_read;
    end else if (((tmp_fu_142_p3 == 1'd0) & (icmp_ln46_fu_129_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_V_2_in_in_fu_40 <= tmp_V_10_fu_135_p2;
    end else if (((grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_tmp_V_20_out_o_ap_vld == 1'b1) & (tmp_reg_256 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_V_2_in_in_fu_40 <= grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_tmp_V_20_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_V_8_fu_48 <= tmp_V_fu_98_p3;
    end else if (((p_Result_s_reg_260 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp_V_8_fu_48 <= grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_p_Val2_28_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        z_V_write_assign_fu_52 <= tmp_V_fu_98_p3;
    end else if (((p_Result_s_reg_260 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        z_V_write_assign_fu_52 <= grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_p_Val2_28_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Result_s_reg_260 <= p_Result_s_fu_172_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_89 <= tmp_V_2_in_in_fu_40;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_129_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_V_10_reg_251[165 : 1] <= tmp_V_10_fu_135_p2[165 : 1];
        tmp_reg_256 <= reg_89[32'd162];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((icmp_ln46_fu_129_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_129_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln46_fu_129_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((p_Result_s_fu_172_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((p_Result_s_fu_172_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln46_fu_195_p2 = (br_fu_44 + 8'd1);

assign and_ln780_fu_167_p2 = (y_V_read & shl_ln780_fu_161_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_done == 1'b0) & (tmp_reg_256 == 1'd1));
end

assign ap_return = z_V_write_assign_fu_52;

assign grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_start = grp_bf_mult_Pipeline_VITIS_LOOP_23_116_fu_78_ap_start_reg;

assign grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_start = grp_bf_mult_Pipeline_VITIS_LOOP_23_1_fu_72_ap_start_reg;

assign icmp_ln46_fu_129_p2 = ((br_fu_44 == 8'd163) ? 1'b1 : 1'b0);

assign p_Result_s_fu_172_p2 = ((and_ln780_fu_167_p2 == 163'd0) ? 1'b1 : 1'b0);

assign shl_ln780_fu_161_p2 = 163'd1 << zext_ln780_fu_158_p1;

assign tmp_V_10_fu_135_p2 = reg_89 << 166'd1;

assign tmp_V_fu_98_p3 = ((trunc_ln36_fu_94_p1[0:0] == 1'b1) ? x_V_read : 166'd0);

assign tmp_fu_142_p3 = reg_89[32'd162];

assign trunc_ln36_fu_94_p1 = y_V_read[0:0];

assign zext_ln780_fu_158_p1 = br_fu_44;

always @ (posedge ap_clk) begin
    tmp_V_10_reg_251[0] <= 1'b0;
end

endmodule //Radix2wECC_bf_mult
