-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Radix2wECC_bf_inv is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (165 downto 0) );
end;


architecture behav of Radix2wECC_bf_inv is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv166_lc_3 : STD_LOGIC_VECTOR (165 downto 0) := "0010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011001001";
    constant ap_const_lv166_lc_1 : STD_LOGIC_VECTOR (165 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv166_lc_2 : STD_LOGIC_VECTOR (165 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_fu_158_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_332 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal j_1_fu_172_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal j_1_reg_340 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_11_reg_346 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln67_fu_191_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal select_ln67_reg_352 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal u_V_fu_210_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal u_V_reg_357 : STD_LOGIC_VECTOR (165 downto 0);
    signal r_V_fu_247_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal r_V_reg_362 : STD_LOGIC_VECTOR (165 downto 0);
    signal r_V_1_fu_266_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal r_V_1_reg_367 : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_done : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_idle : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_ready : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_i_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_i_out_ap_vld : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_done : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_idle : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_ready : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_i_29_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_i_29_out_ap_vld : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_done : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_idle : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_ready : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o_ap_vld : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_done : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_idle : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_ready : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o_ap_vld : STD_LOGIC;
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg : STD_LOGIC := '0';
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal u_V_2_fu_34 : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg : STD_LOGIC := '0';
    signal z_V_write_assign_fu_46 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal v_V_1_fu_38 : STD_LOGIC_VECTOR (165 downto 0);
    signal v_V_fu_205_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal g_V_fu_42 : STD_LOGIC_VECTOR (165 downto 0);
    signal g_V_1_fu_198_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal icmp_ln1023_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln18_fu_132_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln18_1_fu_142_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln18_fu_138_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln66_fu_148_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal j_fu_152_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln70_fu_166_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1669_fu_215_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1669_fu_218_p1 : STD_LOGIC_VECTOR (165 downto 0);
    signal sub_ln1669_fu_228_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1669_1_fu_233_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1669_1_fu_237_p1 : STD_LOGIC_VECTOR (165 downto 0);
    signal ashr_ln1669_fu_241_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal shl_ln1669_fu_222_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal ashr_ln1669_1_fu_260_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal shl_ln1669_1_fu_254_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_block_state8_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_15_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        u_V_4 : IN STD_LOGIC_VECTOR (165 downto 0);
        i_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        i_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_15_117 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        v_V_2 : IN STD_LOGIC_VECTOR (165 downto 0);
        i_29_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        i_29_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_23_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        u_V : IN STD_LOGIC_VECTOR (165 downto 0);
        r_V : IN STD_LOGIC_VECTOR (165 downto 0);
        u_V_5_out_i : IN STD_LOGIC_VECTOR (165 downto 0);
        u_V_5_out_o : OUT STD_LOGIC_VECTOR (165 downto 0);
        u_V_5_out_o_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_23_118 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        select_ln67 : IN STD_LOGIC_VECTOR (165 downto 0);
        r_V_1 : IN STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_33_out_i : IN STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_33_out_o : OUT STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_33_out_o_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64 : component Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_15_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start,
        ap_done => grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_done,
        ap_idle => grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_idle,
        ap_ready => grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_ready,
        u_V_4 => u_V_2_fu_34,
        i_out => grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_i_out,
        i_out_ap_vld => grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_i_out_ap_vld);

    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70 : component Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_15_117
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start,
        ap_done => grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_done,
        ap_idle => grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_idle,
        ap_ready => grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_ready,
        v_V_2 => v_V_1_fu_38,
        i_29_out => grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_i_29_out,
        i_29_out_ap_vld => grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_i_29_out_ap_vld);

    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76 : component Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_23_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start,
        ap_done => grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_done,
        ap_idle => grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_idle,
        ap_ready => grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_ready,
        u_V => u_V_reg_357,
        r_V => r_V_reg_362,
        u_V_5_out_i => u_V_2_fu_34,
        u_V_5_out_o => grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o,
        u_V_5_out_o_ap_vld => grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o_ap_vld);

    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83 : component Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_23_118
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start,
        ap_done => grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_done,
        ap_idle => grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_idle,
        ap_ready => grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_ready,
        select_ln67 => select_ln67_reg_352,
        r_V_1 => r_V_1_reg_367,
        p_Val2_33_out_i => z_V_write_assign_fu_46,
        p_Val2_33_out_o => grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o,
        p_Val2_33_out_o_ap_vld => grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_ready = ap_const_logic_1)) then 
                    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_ready = ap_const_logic_1)) then 
                    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_ready = ap_const_logic_1)) then 
                    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_ready = ap_const_logic_1)) then 
                    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    g_V_fu_42_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                g_V_fu_42 <= ap_const_lv166_lc_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                g_V_fu_42 <= g_V_1_fu_198_p3;
            end if; 
        end if;
    end process;

    u_V_2_fu_34_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                u_V_2_fu_34 <= x_V_read;
            elsif (((grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                u_V_2_fu_34 <= grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_u_V_5_out_o;
            end if; 
        end if;
    end process;

    v_V_1_fu_38_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                v_V_1_fu_38 <= ap_const_lv166_lc_3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                v_V_1_fu_38 <= v_V_fu_205_p3;
            end if; 
        end if;
    end process;

    z_V_write_assign_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                z_V_write_assign_fu_46 <= ap_const_lv166_lc_2;
            elsif (((grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                z_V_write_assign_fu_46 <= grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_p_Val2_33_out_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                j_1_reg_340 <= j_1_fu_172_p3;
                tmp_11_reg_346 <= j_1_fu_172_p3(16 downto 16);
                tmp_reg_332 <= j_fu_152_p2(16 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                r_V_1_reg_367 <= r_V_1_fu_266_p3;
                r_V_reg_362 <= r_V_fu_247_p3;
                select_ln67_reg_352 <= select_ln67_fu_191_p3;
                u_V_reg_357 <= u_V_fu_210_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state8, ap_CS_fsm_state2, icmp_ln1023_fu_116_p2, ap_block_state4_on_subcall_done, ap_block_state8_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln1023_fu_116_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_boolean_0 = ap_block_state8_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln18_1_fu_142_p2 <= std_logic_vector(unsigned(grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_i_29_out) + unsigned(ap_const_lv16_1));
    add_ln18_fu_132_p2 <= std_logic_vector(unsigned(grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_i_out) + unsigned(ap_const_lv16_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_on_subcall_done)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(ap_block_state8_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state8_on_subcall_done)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_done, grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_done)
    begin
                ap_block_state4_on_subcall_done <= ((grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_done = ap_const_logic_0) or (grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_done = ap_const_logic_0));
    end process;


    ap_block_state8_on_subcall_done_assign_proc : process(grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_done, grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_done)
    begin
                ap_block_state8_on_subcall_done <= ((grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_done = ap_const_logic_0) or (grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln1023_fu_116_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln1023_fu_116_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln1023_fu_116_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln1023_fu_116_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= z_V_write_assign_fu_46;
    ashr_ln1669_1_fu_260_p2 <= std_logic_vector(shift_right(signed(g_V_1_fu_198_p3),to_integer(unsigned('0' & zext_ln1669_1_fu_237_p1(31-1 downto 0)))));
    ashr_ln1669_fu_241_p2 <= std_logic_vector(shift_right(signed(v_V_fu_205_p3),to_integer(unsigned('0' & zext_ln1669_1_fu_237_p1(31-1 downto 0)))));
    g_V_1_fu_198_p3 <= 
        z_V_write_assign_fu_46 when (tmp_reg_332(0) = '1') else 
        g_V_fu_42;
    grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start <= grp_bf_inv_Pipeline_VITIS_LOOP_15_117_fu_70_ap_start_reg;
    grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start <= grp_bf_inv_Pipeline_VITIS_LOOP_15_1_fu_64_ap_start_reg;
    grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start <= grp_bf_inv_Pipeline_VITIS_LOOP_23_118_fu_83_ap_start_reg;
    grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start <= grp_bf_inv_Pipeline_VITIS_LOOP_23_1_fu_76_ap_start_reg;
    icmp_ln1023_fu_116_p2 <= "1" when (u_V_2_fu_34 = ap_const_lv166_lc_2) else "0";
    j_1_fu_172_p3 <= 
        sub_ln70_fu_166_p2 when (tmp_fu_158_p3(0) = '1') else 
        j_fu_152_p2;
    j_fu_152_p2 <= std_logic_vector(unsigned(zext_ln18_fu_138_p1) - unsigned(zext_ln66_fu_148_p1));
    r_V_1_fu_266_p3 <= 
        ashr_ln1669_1_fu_260_p2 when (tmp_11_reg_346(0) = '1') else 
        shl_ln1669_1_fu_254_p2;
    r_V_fu_247_p3 <= 
        ashr_ln1669_fu_241_p2 when (tmp_11_reg_346(0) = '1') else 
        shl_ln1669_fu_222_p2;
    select_ln67_fu_191_p3 <= 
        g_V_fu_42 when (tmp_reg_332(0) = '1') else 
        z_V_write_assign_fu_46;
        sext_ln1669_1_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1669_fu_228_p2),32));

        sext_ln1669_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(j_1_reg_340),32));

    shl_ln1669_1_fu_254_p2 <= std_logic_vector(shift_left(unsigned(g_V_1_fu_198_p3),to_integer(unsigned('0' & zext_ln1669_fu_218_p1(31-1 downto 0)))));
    shl_ln1669_fu_222_p2 <= std_logic_vector(shift_left(unsigned(v_V_fu_205_p3),to_integer(unsigned('0' & zext_ln1669_fu_218_p1(31-1 downto 0)))));
    sub_ln1669_fu_228_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(j_1_reg_340));
    sub_ln70_fu_166_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(j_fu_152_p2));
    tmp_fu_158_p3 <= j_fu_152_p2(16 downto 16);
    u_V_fu_210_p3 <= 
        v_V_1_fu_38 when (tmp_reg_332(0) = '1') else 
        u_V_2_fu_34;
    v_V_fu_205_p3 <= 
        u_V_2_fu_34 when (tmp_reg_332(0) = '1') else 
        v_V_1_fu_38;
    zext_ln1669_1_fu_237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1669_1_fu_233_p1),166));
    zext_ln1669_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1669_fu_215_p1),166));
    zext_ln18_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln18_fu_132_p2),17));
    zext_ln66_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln18_1_fu_142_p2),17));
end behav;
