-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Radix2wECC_point_add is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x1_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
    y1_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
    x2_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
    y2_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (165 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (165 downto 0) );
end;


architecture behav of Radix2wECC_point_add is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (27 downto 0) := "0000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (27 downto 0) := "0000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (27 downto 0) := "0000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (27 downto 0) := "0000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (27 downto 0) := "0000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (27 downto 0) := "0000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (27 downto 0) := "0001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (27 downto 0) := "0010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (27 downto 0) := "0100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (27 downto 0) := "1000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv166_lc_1 : STD_LOGIC_VECTOR (165 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv166_lc_2 : STD_LOGIC_VECTOR (165 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_bf_inv_fu_160_ap_return : STD_LOGIC_VECTOR (165 downto 0);
    signal reg_245 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal grp_bf_mult_1_fu_165_ap_return : STD_LOGIC_VECTOR (165 downto 0);
    signal reg_250 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal grp_bf_mult_2_fu_172_ap_return : STD_LOGIC_VECTOR (165 downto 0);
    signal reg_258 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal trunc_ln99_fu_264_p1 : STD_LOGIC_VECTOR (162 downto 0);
    signal trunc_ln99_reg_478 : STD_LOGIC_VECTOR (162 downto 0);
    signal or_ln100_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln100_reg_483 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln101_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln101_reg_487 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_reg_491 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln120_fu_312_p1 : STD_LOGIC_VECTOR (162 downto 0);
    signal trunc_ln120_reg_501 : STD_LOGIC_VECTOR (162 downto 0);
    signal d_V_4_fu_323_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal d_V_4_reg_509 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_bf_mult_fu_200_ap_return : STD_LOGIC_VECTOR (165 downto 0);
    signal a_V_reg_519 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal select_ln108_fu_358_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal lambda_V_5_fu_369_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal lambda_V_5_reg_538 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal call_ret8_reg_544 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal empty_fu_378_p1 : STD_LOGIC_VECTOR (162 downto 0);
    signal empty_reg_552 : STD_LOGIC_VECTOR (162 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_done : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_idle : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out_ap_vld : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_done : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_idle : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out : STD_LOGIC_VECTOR (162 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out_ap_vld : STD_LOGIC;
    signal grp_bf_inv_fu_160_ap_start : STD_LOGIC;
    signal grp_bf_inv_fu_160_ap_done : STD_LOGIC;
    signal grp_bf_inv_fu_160_ap_idle : STD_LOGIC;
    signal grp_bf_inv_fu_160_ap_ready : STD_LOGIC;
    signal grp_bf_inv_fu_160_x_V_read : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_bf_mult_1_fu_165_ap_start : STD_LOGIC;
    signal grp_bf_mult_1_fu_165_ap_done : STD_LOGIC;
    signal grp_bf_mult_1_fu_165_ap_idle : STD_LOGIC;
    signal grp_bf_mult_1_fu_165_ap_ready : STD_LOGIC;
    signal grp_bf_mult_1_fu_165_z_V_read : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_bf_mult_1_fu_165_y_V_read : STD_LOGIC_VECTOR (162 downto 0);
    signal grp_bf_mult_2_fu_172_ap_start : STD_LOGIC;
    signal grp_bf_mult_2_fu_172_ap_done : STD_LOGIC;
    signal grp_bf_mult_2_fu_172_ap_idle : STD_LOGIC;
    signal grp_bf_mult_2_fu_172_ap_ready : STD_LOGIC;
    signal grp_bf_mult_2_fu_172_x_V_read : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_done : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_idle : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_d_V_6_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_d_V_6_out_ap_vld : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_done : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_idle : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_p_Val2_12_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_p_Val2_12_out_ap_vld : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_done : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_idle : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_p_Val2_16_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_p_Val2_16_out_ap_vld : STD_LOGIC;
    signal grp_bf_mult_fu_200_ap_start : STD_LOGIC;
    signal grp_bf_mult_fu_200_ap_done : STD_LOGIC;
    signal grp_bf_mult_fu_200_ap_idle : STD_LOGIC;
    signal grp_bf_mult_fu_200_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_done : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_idle : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_a_V_7_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_a_V_7_out_ap_vld : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_done : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_idle : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out_ap_vld : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_done : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_idle : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out_ap_vld : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_done : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_idle : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out_ap_vld : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_done : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_idle : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_ready : STD_LOGIC;
    signal grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_p_Val2_14_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_p_Val2_14_out_ap_vld : STD_LOGIC;
    signal ap_phi_mux_x1_3_phi_fu_113_p10 : STD_LOGIC_VECTOR (165 downto 0);
    signal x1_3_reg_110 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_CS_fsm_state28 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal icmp_ln108_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_y1_2_phi_fu_129_p10 : STD_LOGIC_VECTOR (165 downto 0);
    signal y1_2_reg_125 : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg : STD_LOGIC := '0';
    signal p_Val2_8_loc_fu_66 : STD_LOGIC_VECTOR (162 downto 0);
    signal grp_bf_inv_fu_160_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_bf_mult_1_fu_165_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state19_on_subcall_done : BOOLEAN;
    signal grp_bf_mult_2_fu_172_ap_start_reg : STD_LOGIC := '0';
    signal grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal grp_bf_mult_fu_200_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state27 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state27 : signal is "none";
    signal icmp_ln1023_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1023_2_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln101_fu_286_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (165 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (165 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_17 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x1_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        x2_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        a_V_6_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        a_V_6_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_18 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y1_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        y2_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_8_out : OUT STD_LOGIC_VECTOR (162 downto 0);
        p_Val2_8_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_bf_inv IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (165 downto 0) );
    end component;


    component Radix2wECC_bf_mult_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        z_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        y_V_read : IN STD_LOGIC_VECTOR (162 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (165 downto 0) );
    end component;


    component Radix2wECC_bf_mult_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (165 downto 0) );
    end component;


    component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_19 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        d_V : IN STD_LOGIC_VECTOR (165 downto 0);
        c_V_3 : IN STD_LOGIC_VECTOR (165 downto 0);
        d_V_6_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        d_V_6_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_110 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        d_V_6_reload : IN STD_LOGIC_VECTOR (165 downto 0);
        a_V_6_reload : IN STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_12_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_12_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_111 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x1_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        d_V_7 : IN STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_16_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_16_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_bf_mult IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        y_V_read : IN STD_LOGIC_VECTOR (162 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (165 downto 0) );
    end component;


    component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_112 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        a_V : IN STD_LOGIC_VECTOR (165 downto 0);
        d_V_7 : IN STD_LOGIC_VECTOR (165 downto 0);
        a_V_7_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        a_V_7_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_113 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y1_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        a_V_7_reload : IN STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_19_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_19_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        lambda_V_7 : IN STD_LOGIC_VECTOR (165 downto 0);
        x2_V_read : IN STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_7_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_7_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_15 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        call_ret8 : IN STD_LOGIC_VECTOR (165 downto 0);
        lambda_V_11 : IN STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_9_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_9_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_16 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        call_ret7 : IN STD_LOGIC_VECTOR (165 downto 0);
        lambda_V_12 : IN STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_14_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        p_Val2_14_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142 : component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_17
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start,
        ap_done => grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_done,
        ap_idle => grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_idle,
        ap_ready => grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_ready,
        x1_V_read => x1_V_read,
        x2_V_read => x2_V_read,
        a_V_6_out => grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out,
        a_V_6_out_ap_vld => grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out_ap_vld);

    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151 : component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_18
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start,
        ap_done => grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_done,
        ap_idle => grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_idle,
        ap_ready => grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_ready,
        y1_V_read => y1_V_read,
        y2_V_read => y2_V_read,
        p_Val2_8_out => grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out,
        p_Val2_8_out_ap_vld => grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out_ap_vld);

    grp_bf_inv_fu_160 : component Radix2wECC_bf_inv
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bf_inv_fu_160_ap_start,
        ap_done => grp_bf_inv_fu_160_ap_done,
        ap_idle => grp_bf_inv_fu_160_ap_idle,
        ap_ready => grp_bf_inv_fu_160_ap_ready,
        x_V_read => grp_bf_inv_fu_160_x_V_read,
        ap_return => grp_bf_inv_fu_160_ap_return);

    grp_bf_mult_1_fu_165 : component Radix2wECC_bf_mult_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bf_mult_1_fu_165_ap_start,
        ap_done => grp_bf_mult_1_fu_165_ap_done,
        ap_idle => grp_bf_mult_1_fu_165_ap_idle,
        ap_ready => grp_bf_mult_1_fu_165_ap_ready,
        z_V_read => grp_bf_mult_1_fu_165_z_V_read,
        y_V_read => grp_bf_mult_1_fu_165_y_V_read,
        ap_return => grp_bf_mult_1_fu_165_ap_return);

    grp_bf_mult_2_fu_172 : component Radix2wECC_bf_mult_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bf_mult_2_fu_172_ap_start,
        ap_done => grp_bf_mult_2_fu_172_ap_done,
        ap_idle => grp_bf_mult_2_fu_172_ap_idle,
        ap_ready => grp_bf_mult_2_fu_172_ap_ready,
        x_V_read => grp_bf_mult_2_fu_172_x_V_read,
        ap_return => grp_bf_mult_2_fu_172_ap_return);

    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178 : component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_19
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start,
        ap_done => grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_done,
        ap_idle => grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_idle,
        ap_ready => grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_ready,
        d_V => reg_258,
        c_V_3 => reg_250,
        d_V_6_out => grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_d_V_6_out,
        d_V_6_out_ap_vld => grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_d_V_6_out_ap_vld);

    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186 : component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_110
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start,
        ap_done => grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_done,
        ap_idle => grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_idle,
        ap_ready => grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_ready,
        d_V_6_reload => grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_d_V_6_out,
        a_V_6_reload => grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out,
        p_Val2_12_out => grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_p_Val2_12_out,
        p_Val2_12_out_ap_vld => grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_p_Val2_12_out_ap_vld);

    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193 : component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_111
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start,
        ap_done => grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_done,
        ap_idle => grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_idle,
        ap_ready => grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_ready,
        x1_V_read => x1_V_read,
        d_V_7 => d_V_4_reg_509,
        p_Val2_16_out => grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_p_Val2_16_out,
        p_Val2_16_out_ap_vld => grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_p_Val2_16_out_ap_vld);

    grp_bf_mult_fu_200 : component Radix2wECC_bf_mult
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bf_mult_fu_200_ap_start,
        ap_done => grp_bf_mult_fu_200_ap_done,
        ap_idle => grp_bf_mult_fu_200_ap_idle,
        ap_ready => grp_bf_mult_fu_200_ap_ready,
        x_V_read => grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_p_Val2_16_out,
        y_V_read => trunc_ln120_reg_501,
        ap_return => grp_bf_mult_fu_200_ap_return);

    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206 : component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_112
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start,
        ap_done => grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_done,
        ap_idle => grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_idle,
        ap_ready => grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_ready,
        a_V => a_V_reg_519,
        d_V_7 => d_V_4_reg_509,
        a_V_7_out => grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_a_V_7_out,
        a_V_7_out_ap_vld => grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_a_V_7_out_ap_vld);

    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214 : component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_113
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start,
        ap_done => grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_done,
        ap_idle => grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_idle,
        ap_ready => grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_ready,
        y1_V_read => y1_V_read,
        a_V_7_reload => grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_a_V_7_out,
        p_Val2_19_out => grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out,
        p_Val2_19_out_ap_vld => grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out_ap_vld);

    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221 : component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start,
        ap_done => grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_done,
        ap_idle => grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_idle,
        ap_ready => grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_ready,
        lambda_V_7 => reg_250,
        x2_V_read => x2_V_read,
        p_Val2_7_out => grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out,
        p_Val2_7_out_ap_vld => grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out_ap_vld);

    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229 : component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_15
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start,
        ap_done => grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_done,
        ap_idle => grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_idle,
        ap_ready => grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_ready,
        call_ret8 => call_ret8_reg_544,
        lambda_V_11 => lambda_V_5_reg_538,
        p_Val2_9_out => grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out,
        p_Val2_9_out_ap_vld => grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out_ap_vld);

    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237 : component Radix2wECC_point_add_Pipeline_VITIS_LOOP_23_16
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start,
        ap_done => grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_done,
        ap_idle => grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_idle,
        ap_ready => grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_ready,
        call_ret7 => reg_258,
        lambda_V_12 => reg_250,
        p_Val2_14_out => grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_p_Val2_14_out,
        p_Val2_14_out_ap_vld => grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_p_Val2_14_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv166_lc_1;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                    ap_return_0_preg <= ap_phi_mux_x1_3_phi_fu_113_p10;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv166_lc_1;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                    ap_return_1_preg <= ap_phi_mux_y1_2_phi_fu_129_p10;
                end if; 
            end if;
        end if;
    end process;


    grp_bf_inv_fu_160_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bf_inv_fu_160_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln108_fu_354_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18)))) then 
                    grp_bf_inv_fu_160_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bf_inv_fu_160_ap_ready = ap_const_logic_1)) then 
                    grp_bf_inv_fu_160_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_bf_mult_1_fu_165_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bf_mult_1_fu_165_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state25) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_bf_inv_fu_160_ap_done = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_state19_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state19)))) then 
                    grp_bf_mult_1_fu_165_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bf_mult_1_fu_165_ap_ready = ap_const_logic_1)) then 
                    grp_bf_mult_1_fu_165_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_bf_mult_2_fu_172_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bf_mult_2_fu_172_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state22) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_bf_mult_1_fu_165_ap_done = ap_const_logic_1)) or ((icmp_ln108_fu_354_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18)))) then 
                    grp_bf_mult_2_fu_172_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bf_mult_2_fu_172_ap_ready = ap_const_logic_1)) then 
                    grp_bf_mult_2_fu_172_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_bf_mult_fu_200_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bf_mult_fu_200_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                    grp_bf_mult_fu_200_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bf_mult_fu_200_ap_ready = ap_const_logic_1)) then 
                    grp_bf_mult_fu_200_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_ready = ap_const_logic_1)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_ready = ap_const_logic_1)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg <= ap_const_logic_0;
            else
                if (((grp_bf_mult_fu_200_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_ready = ap_const_logic_1)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_ready = ap_const_logic_1)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state23) and (grp_bf_mult_2_fu_172_ap_done = ap_const_logic_1))) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_ready = ap_const_logic_1)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state26) and (grp_bf_mult_1_fu_165_ap_done = ap_const_logic_1))) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_ready = ap_const_logic_1)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln1019_fu_298_p2 = ap_const_lv1_0) and (icmp_ln101_fu_292_p2 = ap_const_lv1_0) and (or_ln100_fu_280_p2 = ap_const_lv1_0))) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_ready = ap_const_logic_1)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln1019_fu_298_p2 = ap_const_lv1_0) and (icmp_ln101_fu_292_p2 = ap_const_lv1_0) and (or_ln100_fu_280_p2 = ap_const_lv1_0))) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_ready = ap_const_logic_1)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_bf_mult_2_fu_172_ap_done = ap_const_logic_1))) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_ready = ap_const_logic_1)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state20) and (grp_bf_mult_1_fu_165_ap_done = ap_const_logic_1))) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_ready = ap_const_logic_1)) then 
                    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    x1_3_reg_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln108_fu_354_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                x1_3_reg_110 <= select_ln108_fu_358_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln101_fu_292_p2 = ap_const_lv1_1) and (or_ln100_fu_280_p2 = ap_const_lv1_0))) then 
                x1_3_reg_110 <= x2_V_read;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (or_ln100_fu_280_p2 = ap_const_lv1_1))) then 
                x1_3_reg_110 <= x1_V_read;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state28)) then 
                x1_3_reg_110 <= grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state17) and (icmp_ln1019_reg_491 = ap_const_lv1_0) and (icmp_ln101_reg_487 = ap_const_lv1_0) and (or_ln100_reg_483 = ap_const_lv1_0))) then 
                x1_3_reg_110 <= d_V_4_reg_509;
            end if; 
        end if;
    end process;

    y1_2_reg_125_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln108_fu_354_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                y1_2_reg_125 <= ap_const_lv166_lc_1;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln101_fu_292_p2 = ap_const_lv1_1) and (or_ln100_fu_280_p2 = ap_const_lv1_0))) then 
                y1_2_reg_125 <= y2_V_read;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (or_ln100_fu_280_p2 = ap_const_lv1_1))) then 
                y1_2_reg_125 <= y1_V_read;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state28)) then 
                y1_2_reg_125 <= grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_p_Val2_14_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state17) and (icmp_ln1019_reg_491 = ap_const_lv1_0) and (icmp_ln101_reg_487 = ap_const_lv1_0) and (or_ln100_reg_483 = ap_const_lv1_0))) then 
                y1_2_reg_125 <= grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                a_V_reg_519 <= grp_bf_mult_fu_200_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then
                call_ret8_reg_544 <= grp_bf_mult_2_fu_172_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                d_V_4_reg_509 <= d_V_4_fu_323_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state25)) then
                empty_reg_552 <= empty_fu_378_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln101_fu_292_p2 = ap_const_lv1_0) and (or_ln100_fu_280_p2 = ap_const_lv1_0))) then
                icmp_ln1019_reg_491 <= icmp_ln1019_fu_298_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (or_ln100_fu_280_p2 = ap_const_lv1_0))) then
                icmp_ln101_reg_487 <= icmp_ln101_fu_292_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state22)) then
                lambda_V_5_reg_538 <= lambda_V_5_fu_369_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                or_ln100_reg_483 <= or_ln100_fu_280_p2;
                trunc_ln99_reg_478 <= trunc_ln99_fu_264_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out_ap_vld = ap_const_logic_1))) then
                p_Val2_8_loc_fu_66 <= grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_p_Val2_8_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state4))) then
                reg_245 <= grp_bf_inv_fu_160_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state26) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state5))) then
                reg_250 <= grp_bf_mult_1_fu_165_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state19))) then
                reg_258 <= grp_bf_mult_2_fu_172_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                trunc_ln120_reg_501 <= trunc_ln120_fu_312_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state19, ap_CS_fsm_state5, ap_CS_fsm_state20, ap_CS_fsm_state26, ap_CS_fsm_state6, or_ln100_fu_280_p2, icmp_ln101_fu_292_p2, icmp_ln1019_fu_298_p2, ap_CS_fsm_state13, ap_CS_fsm_state18, ap_CS_fsm_state23, grp_bf_inv_fu_160_ap_done, grp_bf_mult_1_fu_165_ap_done, grp_bf_mult_2_fu_172_ap_done, grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_done, grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_done, grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_done, grp_bf_mult_fu_200_ap_done, grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_done, grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_done, grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_done, grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_done, grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_done, icmp_ln108_fu_354_p2, ap_CS_fsm_state2, ap_block_state19_on_subcall_done, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state14, ap_CS_fsm_state16, ap_CS_fsm_state21, ap_CS_fsm_state24, ap_CS_fsm_state27, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln1019_fu_298_p2 = ap_const_lv1_1) and (icmp_ln101_fu_292_p2 = ap_const_lv1_0) and (or_ln100_fu_280_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln1019_fu_298_p2 = ap_const_lv1_0) and (icmp_ln101_fu_292_p2 = ap_const_lv1_0) and (or_ln100_fu_280_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((icmp_ln101_fu_292_p2 = ap_const_lv1_1) or (or_ln100_fu_280_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_bf_inv_fu_160_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_bf_mult_1_fu_165_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_bf_mult_2_fu_172_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((grp_bf_mult_fu_200_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                if (((grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                if (((grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state18 => 
                if (((icmp_ln108_fu_354_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when ap_ST_fsm_state19 => 
                if (((ap_const_boolean_0 = ap_block_state19_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state20 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state20) and (grp_bf_mult_1_fu_165_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state21 => 
                if (((grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state21))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_state21;
                end if;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state23) and (grp_bf_mult_2_fu_172_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state24;
                else
                    ap_NS_fsm <= ap_ST_fsm_state23;
                end if;
            when ap_ST_fsm_state24 => 
                if (((grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state24))) then
                    ap_NS_fsm <= ap_ST_fsm_state25;
                else
                    ap_NS_fsm <= ap_ST_fsm_state24;
                end if;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state26) and (grp_bf_mult_1_fu_165_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state27;
                else
                    ap_NS_fsm <= ap_ST_fsm_state26;
                end if;
            when ap_ST_fsm_state27 => 
                if (((grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state27))) then
                    ap_NS_fsm <= ap_ST_fsm_state28;
                else
                    ap_NS_fsm <= ap_ST_fsm_state27;
                end if;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state27 <= ap_CS_fsm(26);
    ap_CS_fsm_state28 <= ap_CS_fsm(27);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_done)
    begin
        if ((grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(grp_bf_mult_fu_200_ap_done)
    begin
        if ((grp_bf_mult_fu_200_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state14_blk_assign_proc : process(grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_done)
    begin
        if ((grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state15_blk <= ap_const_logic_0;

    ap_ST_fsm_state16_blk_assign_proc : process(grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_done)
    begin
        if ((grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state16_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state16_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;

    ap_ST_fsm_state19_blk_assign_proc : process(ap_block_state19_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state19_on_subcall_done)) then 
            ap_ST_fsm_state19_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state19_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state20_blk_assign_proc : process(grp_bf_mult_1_fu_165_ap_done)
    begin
        if ((grp_bf_mult_1_fu_165_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state20_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state20_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state21_blk_assign_proc : process(grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_done)
    begin
        if ((grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state21_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state21_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state22_blk <= ap_const_logic_0;

    ap_ST_fsm_state23_blk_assign_proc : process(grp_bf_mult_2_fu_172_ap_done)
    begin
        if ((grp_bf_mult_2_fu_172_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state23_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state23_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state24_blk_assign_proc : process(grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_done)
    begin
        if ((grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state24_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state24_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state25_blk <= ap_const_logic_0;

    ap_ST_fsm_state26_blk_assign_proc : process(grp_bf_mult_1_fu_165_ap_done)
    begin
        if ((grp_bf_mult_1_fu_165_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state26_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state26_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state27_blk_assign_proc : process(grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_done)
    begin
        if ((grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state27_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state27_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state28_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_bf_inv_fu_160_ap_done)
    begin
        if ((grp_bf_inv_fu_160_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(grp_bf_mult_1_fu_165_ap_done)
    begin
        if ((grp_bf_mult_1_fu_165_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(grp_bf_mult_2_fu_172_ap_done)
    begin
        if ((grp_bf_mult_2_fu_172_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state7_blk_assign_proc : process(grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_done)
    begin
        if ((grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_done)
    begin
        if ((grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state19_on_subcall_done_assign_proc : process(grp_bf_inv_fu_160_ap_done, grp_bf_mult_2_fu_172_ap_done)
    begin
                ap_block_state19_on_subcall_done <= ((grp_bf_mult_2_fu_172_ap_done = ap_const_logic_0) or (grp_bf_inv_fu_160_ap_done = ap_const_logic_0));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_done, grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_done = ap_const_logic_0) or (grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_x1_3_phi_fu_113_p10_assign_proc : process(or_ln100_reg_483, icmp_ln101_reg_487, icmp_ln1019_reg_491, d_V_4_reg_509, x1_3_reg_110, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) and (icmp_ln1019_reg_491 = ap_const_lv1_0) and (icmp_ln101_reg_487 = ap_const_lv1_0) and (or_ln100_reg_483 = ap_const_lv1_0))) then 
            ap_phi_mux_x1_3_phi_fu_113_p10 <= d_V_4_reg_509;
        else 
            ap_phi_mux_x1_3_phi_fu_113_p10 <= x1_3_reg_110;
        end if; 
    end process;


    ap_phi_mux_y1_2_phi_fu_129_p10_assign_proc : process(or_ln100_reg_483, icmp_ln101_reg_487, icmp_ln1019_reg_491, grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out, ap_CS_fsm_state17, y1_2_reg_125)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) and (icmp_ln1019_reg_491 = ap_const_lv1_0) and (icmp_ln101_reg_487 = ap_const_lv1_0) and (or_ln100_reg_483 = ap_const_lv1_0))) then 
            ap_phi_mux_y1_2_phi_fu_129_p10 <= grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_p_Val2_19_out;
        else 
            ap_phi_mux_y1_2_phi_fu_129_p10 <= y1_2_reg_125;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_phi_mux_x1_3_phi_fu_113_p10, ap_CS_fsm_state17, ap_return_0_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            ap_return_0 <= ap_phi_mux_x1_3_phi_fu_113_p10;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_state17, ap_phi_mux_y1_2_phi_fu_129_p10, ap_return_1_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            ap_return_1 <= ap_phi_mux_y1_2_phi_fu_129_p10;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;

    d_V_4_fu_323_p2 <= (grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_p_Val2_12_out xor ap_const_lv166_lc_2);
    empty_fu_378_p1 <= grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_p_Val2_9_out(163 - 1 downto 0);
    grp_bf_inv_fu_160_ap_start <= grp_bf_inv_fu_160_ap_start_reg;

    grp_bf_inv_fu_160_x_V_read_assign_proc : process(x2_V_read, ap_CS_fsm_state4, ap_CS_fsm_state19, grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_bf_inv_fu_160_x_V_read <= x2_V_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_bf_inv_fu_160_x_V_read <= grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_a_V_6_out;
        else 
            grp_bf_inv_fu_160_x_V_read <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_bf_mult_1_fu_165_ap_start <= grp_bf_mult_1_fu_165_ap_start_reg;

    grp_bf_mult_1_fu_165_y_V_read_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state20, ap_CS_fsm_state26, trunc_ln99_reg_478, empty_reg_552, p_Val2_8_loc_fu_66)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            grp_bf_mult_1_fu_165_y_V_read <= empty_reg_552;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_bf_mult_1_fu_165_y_V_read <= trunc_ln99_reg_478;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_bf_mult_1_fu_165_y_V_read <= p_Val2_8_loc_fu_66;
        else 
            grp_bf_mult_1_fu_165_y_V_read <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_bf_mult_1_fu_165_z_V_read_assign_proc : process(reg_245, ap_CS_fsm_state5, ap_CS_fsm_state20, ap_CS_fsm_state26, lambda_V_5_reg_538)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            grp_bf_mult_1_fu_165_z_V_read <= lambda_V_5_reg_538;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            grp_bf_mult_1_fu_165_z_V_read <= reg_245;
        else 
            grp_bf_mult_1_fu_165_z_V_read <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_bf_mult_2_fu_172_ap_start <= grp_bf_mult_2_fu_172_ap_start_reg;

    grp_bf_mult_2_fu_172_x_V_read_assign_proc : process(x2_V_read, ap_CS_fsm_state19, reg_250, ap_CS_fsm_state6, ap_CS_fsm_state23, grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            grp_bf_mult_2_fu_172_x_V_read <= grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_bf_mult_2_fu_172_x_V_read <= x2_V_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_bf_mult_2_fu_172_x_V_read <= reg_250;
        else 
            grp_bf_mult_2_fu_172_x_V_read <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_bf_mult_fu_200_ap_start <= grp_bf_mult_fu_200_ap_start_reg;
    grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start <= grp_point_add_Pipeline_VITIS_LOOP_23_110_fu_186_ap_start_reg;
    grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start <= grp_point_add_Pipeline_VITIS_LOOP_23_111_fu_193_ap_start_reg;
    grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start <= grp_point_add_Pipeline_VITIS_LOOP_23_112_fu_206_ap_start_reg;
    grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start <= grp_point_add_Pipeline_VITIS_LOOP_23_113_fu_214_ap_start_reg;
    grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start <= grp_point_add_Pipeline_VITIS_LOOP_23_15_fu_229_ap_start_reg;
    grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start <= grp_point_add_Pipeline_VITIS_LOOP_23_16_fu_237_ap_start_reg;
    grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start <= grp_point_add_Pipeline_VITIS_LOOP_23_17_fu_142_ap_start_reg;
    grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start <= grp_point_add_Pipeline_VITIS_LOOP_23_18_fu_151_ap_start_reg;
    grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start <= grp_point_add_Pipeline_VITIS_LOOP_23_19_fu_178_ap_start_reg;
    grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start <= grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_ap_start_reg;
    icmp_ln1019_fu_298_p2 <= "1" when (x1_V_read = x2_V_read) else "0";
    icmp_ln101_fu_292_p2 <= "1" when (or_ln101_fu_286_p2 = ap_const_lv166_lc_1) else "0";
    icmp_ln1023_2_fu_274_p2 <= "1" when (y2_V_read = ap_const_lv166_lc_1) else "0";
    icmp_ln1023_fu_268_p2 <= "1" when (x2_V_read = ap_const_lv166_lc_1) else "0";
    icmp_ln108_fu_354_p2 <= "0" when (y1_V_read = y2_V_read) else "1";
    lambda_V_5_fu_369_p2 <= (grp_point_add_Pipeline_VITIS_LOOP_23_1_fu_221_p_Val2_7_out xor ap_const_lv166_lc_2);
    or_ln100_fu_280_p2 <= (icmp_ln1023_fu_268_p2 or icmp_ln1023_2_fu_274_p2);
    or_ln101_fu_286_p2 <= (y1_V_read or x1_V_read);
    select_ln108_fu_358_p3 <= 
        ap_const_lv166_lc_1 when (icmp_ln108_fu_354_p2(0) = '1') else 
        x2_V_read;
    trunc_ln120_fu_312_p1 <= grp_bf_mult_1_fu_165_ap_return(163 - 1 downto 0);
    trunc_ln99_fu_264_p1 <= y2_V_read(163 - 1 downto 0);
end behav;
